
const PLAYLISTS_REQUESTED = 'all/PLAYLISTS_REQUESTED';
const PLAYLISTS_RECEIVED = 'all/PLAYLISTS_RECEIVED';
const PLAYLISTS_ERROR = 'all/PLAYLISTS_ERROR';
const VIDEOS_REQUESTED = 'all/VIDEOS_REQUESTED';
const VIDEOS_RECEIVED = 'all/VIDEOS_RECEIVED';
const VIDEOS_ERROR = 'all/VIDEOS_ERROR';
const VIDEO_REQUESTED = 'one/VIDEO_REQUESTED';
const VIDEO_RECEIVED = 'one/VIDEO_RECEIVED';
const VIDEO_ERROR = 'one/VIDEO_ERROR';


const Actions = {
  PLAYLISTS_REQUESTED,
  PLAYLISTS_RECEIVED,
  PLAYLISTS_ERROR,
  VIDEOS_REQUESTED,
  VIDEOS_RECEIVED,
  VIDEOS_ERROR,
  VIDEO_REQUESTED,
  VIDEO_RECEIVED,
  VIDEO_ERROR
};

export default Actions;

