
const EMPLOYEES_REQUESTED = 'all/EMPLOYEES_REQUESTED';
const EMPLOYEES_RECEIVED = 'all/EMPLOYESS_RECEIVED';
const EMPLOYEES_ERROR = 'all/EMPLOYEES_ERROR';
const EMPLOYEE_REQUESTED = 'one/EMPLOYEE_REQUESTED';
const EMPLOYEE_RECEIVED = 'one/EMPLOYEE_RECEIVED';
const EMPLOYEE_ERROR = 'one/EMPLOYEE_ERROR';


const Actions = {
  EMPLOYEES_REQUESTED,
  EMPLOYEES_RECEIVED,
  EMPLOYEES_ERROR,
  EMPLOYEE_REQUESTED,
  EMPLOYEE_RECEIVED,
  EMPLOYEE_ERROR
};

export default Actions;

