
const EMPLOYEES_REQUESTED = 'all/EMPLOYEES_REQUESTED';
const EMPLOYEES_RECEIVED = 'all/EMPLOYESS_RECEIVED';
const EMPLOYEES_ERROR = 'all/EMPLOYEES_ERROR';
const SET_EMPLOYEE_REQUESTED = 'one/SET_EMPLOYEE_REQUESTED';


const Actions = {
  EMPLOYEES_REQUESTED,
  EMPLOYEES_RECEIVED,
  EMPLOYEES_ERROR,
  SET_EMPLOYEE_REQUESTED
};

export default Actions;

